=== metno/wdb-netcdf/wdb-netcdf-java/etc/wdb_config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="DataType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="double" />
			<xs:enumeration value="float" />
			<xs:enumeration value="int" />
			<xs:enumeration value="short" />
			<xs:enumeration value="char" />
			<xs:enumeration value="String" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="attribute_type">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" use="required" />
		<xs:attribute name="type" type="DataType" default="String" />
	</xs:complexType>

	<xs:complexType name="attribute_list">
		<xs:sequence>
			<xs:element name="attribute" type="attribute_type"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="translation">
		<xs:attribute name="wdbname" type="xs:string" use="required" />
		<xs:attribute name="cfname" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="translation_list">
		<xs:sequence>
			<xs:element name="translation" type="translation"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="parameter_type">
		<xs:complexContent>
			<xs:extension base="translation">
				<xs:sequence>
					<xs:element name="attribute" type="attribute_type"
						minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- <xs:complexType name="parameter_type"> <xs:complexContent> <xs:extension 
		base="attribute_list"> <xs:attribute name="wdbname" type="xs:string" use="required" 
		/> <xs:attribute name="cfname" type="xs:string" /> </xs:extension> </xs:complexContent> 
		</xs:complexType> -->

	<xs:complexType name="complete_parameter_list">
		<xs:sequence>
			<xs:element name="level_parameter" type="parameter_type"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="value_parameter" type="parameter_type"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="wdb_config_type">
		<xs:sequence>
			<xs:element name="global_attributes" type="attribute_list" minOccurs="0" />
			<xs:element name="units" type="translation_list" minOccurs="0" />
			<xs:element name="wdb_parameters" type="complete_parameter_list" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>


	<xs:element name="wdb_netcdf_config" type="wdb_config_type" />


</xs:schema>

=== metno/wdb-netcdf/wdb-netcdf-java/etc/wdb_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wdb_fimex_config>

<wdb_netcdf_config 
	xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="wdb_config.xsd">

<global_attributes>
    <attribute name="Conventions" value="CF-1.0" />
    <attribute name="institution" value="Norwegian Meteorological Institute" />
    <attribute name="topiccategory" value="ClimatologyMeteorologyAtmosphere" />
    <attribute name="distribution_statement" value="Free" />
</global_attributes>

<units>
	<translation wdbname="ratio" cfname="1"/>
	<translation wdbname="%" cfname="%"/>
	<translation wdbname="kg/m2" cfname="kg m-2"/>
	<translation wdbname="m" cfname="m"/>
	<translation wdbname="m2/s2" cfname="m-2 s-2"/>
	<translation wdbname="m/s" cfname="m s-1"/>
	<translation wdbname="Pa" cfname="Pa"/>
	<translation wdbname="s" cfname="s"/>
	<translation wdbname="W/m2" cfname="W m-2"/>
</units>

<wdb_parameters>

	<level_parameter wdbname="height above ground">
	    <attribute name="standard_name" value="height" />
	</level_parameter>
	
	<level_parameter wdbname="height above ground distance">
	    <attribute name="standard_name" value="height" />
	</level_parameter>
	
	
	<value_parameter wdbname="geopotential height specific energy">
	    <attribute name="standard_name" value="geopotential_height" />
	</value_parameter>
	

	<value_parameter wdbname="mean sea level pressure">
	    <attribute name="standard_name" value="air_pressure_at_sea_level" />
	</value_parameter>
			
	<value_parameter wdbname="sea temperature">
	    <attribute name="standard_name" value="sea_water_temperature" />
	</value_parameter>
	
	<value_parameter wdbname="significant combined wind waves and swell height distance">
	    <attribute name="standard_name" value="sea_surface_swell_wave_significant_height" />
	</value_parameter>
	
	<value_parameter wdbname="sunshine duration">
	    <attribute name="standard_name" value="duration_of_sunshine" />
	</value_parameter>
	
	<value_parameter wdbname="total cloud cover">
	    <attribute name="standard_name" value="cloud_area_fraction" />
	</value_parameter>
	
	<value_parameter wdbname="total precipitation distance">
	    <attribute name="standard_name" value="lwe_thickness_of_precipitation_amount" />
	</value_parameter>
	
	<value_parameter wdbname="visibility distance">
	    <attribute name="standard_name" value="visibility_in_air" />
	</value_parameter>
	
	<value_parameter wdbname="wind velocity (u vector)">
	    <attribute name="standard_name" value="x_wind" />
	</value_parameter>
	
	<value_parameter wdbname="wind velocity (v vector)">
	    <attribute name="standard_name" value="y_wind" />
	</value_parameter>
	
	<value_parameter wdbname="x wind">
	    <attribute name="standard_name" value="x_wind" />
	</value_parameter>
	
	<value_parameter wdbname="y wind">
	    <attribute name="standard_name" value="y_wind" />
	</value_parameter>


	<!-- 
	<value_parameter wdbname="local 20th percentile accumulated precipitation surface density">
	    <attribute name="units" value= />
	    <attribute name="standard_name" value= />
	</value_parameter>
	 -->
	
	<!-- 
	<value_parameter wdbname="local 50th percentile accumulated precipitation surface density">
	    <attribute name="units" value= />
	    <attribute name="standard_name" value= />
	</value_parameter>
	 -->
	
	<!-- 
	<value_parameter wdbname="local 80th percentile accumulated precipitation surface density">
	    <attribute name="units" value= />
	    <attribute name="standard_name" value= />
	</value_parameter>
	 -->

	<!-- 
	<value_parameter wdbname="probability of precipitation">
	    <attribute name="units" value= />
	    <attribute name="standard_name" value= />
	</value_parameter>
	 -->
	
	<!-- 
	<value_parameter wdbname="low cloud cover">
	    <attribute name="units" value= />
	    <attribute name="standard_name" value= />
	</value_parameter>
	 -->
	
	<!-- 
	<value_parameter wdbname="medium cloud cover">
	    <attribute name="units" value= />
	    <attribute name="standard_name" value= />
	</value_parameter>
	 -->

	<!-- 
	<value_parameter wdbname="high cloud cover">
	    <attribute name="units" value= />
	    <attribute name="standard_name" value= />
	</value_parameter>
	 -->

</wdb_parameters>
</wdb_netcdf_config>
